export const FETCH_USER = 'FETCH_USER';
export const FETCH_USER_LOADING = 'FETCH_USER_LOADING';
export const FETCH_USER_FAILED = 'FETCH_USER_FAILED';
export const ENTER_DEMO_MODE = 'ENTER_DEMO_MODE';

export const UPDATE_DRAFTS = 'UPDATE_DRAFTS';
export const UPDATE_READING_LIST = 'UPDATE_READING_LIST';
